#!/usr/bin/env node
/**
 * Context Prune — the one command an over-budget owner runs
 * --------------------------------------------------------------
 * Companion to context-weight.mjs. Finds explicitly archive-eligible AGED entries inside the files
 * a session reads at startup and proposes moving them to an archive file
 * beside their source, leaving a pointer where each run of entries stood.
 *
 *   PROPOSE (default)  prints what would move, tokens saved, projected band.
 *                      Writes nothing. This is the mode the doctor offers.
 *   --apply            preserve -> verify -> replace, in that order:
 *                        1. append the entries to {dir}/archive/{YYYY-MM}-{name}.md
 *                        2. read the archive back; every entry must be found
 *                           byte-for-byte, or NOTHING is removed from the source
 *                        3. only then rewrite the source with pointers, and
 *                           read it back to verify the entries are gone
 *                      Never a bare delete. Replacement uses a verified temporary sibling and atomic rename.
 *
 * What counts as an aged entry (units):
 *   Each unit must carry [archive-eligible]; [pinned] and standing rule/policy
 *   markers exclude it. Age alone is never authorization.
 *   - a section (## / ###) whose heading carries a date older than --days
 *   - a top-level list item whose first line carries a date older than --days
 *   In the chief-of-staff entry file ONLY the preferences / lessons section is
 *   eligible - instructions are never pruned. Files that declare themselves
 *   GENERATED (a task index, a baked report) are refused: the cap belongs in
 *   their generator, and hand-editing a generated file is lost on the next bake.
 *
 * Run:   node tools/context-prune.mjs                   (propose, all startup files)
 *        node tools/context-prune.mjs --file dean/memory.md --days 45
 *        node tools/context-prune.mjs --apply           (do it, with the checks above)
 * Flags: --root --days N (30) --file REL --today YYYY-MM-DD --window N --json
 * Exit:  0 nothing to do or applied cleanly . 1 proposal has moves . 2 a verify step failed
 * Dependency-free (node:fs, node:path, node:child_process only).
 */

import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { applyPlan, contained } from './prune-write.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
function flag(name, dflt) { const i = argv.indexOf('--' + name); if (i < 0) return dflt; const v = argv[i + 1]; return (v === undefined || v.startsWith('--')) ? true : v; }
const APPLY = argv.includes('--apply');
const JSON_OUT = argv.includes('--json');
const DAYS = Number(flag('days', 30));
const ONLY = flag('file', null);
const TODAY = String(flag('today', new Date().toISOString().slice(0, 10)));
const WINDOW = Number(flag('window', process.env.CONTEXT_WINDOW || 200000));
const ROOT_ARG = flag('root', process.env.CAMPUS_ROOT || null);

const tokens = s => Math.round(Buffer.byteLength(s, 'utf8') / 4);
const fmt = n => n.toLocaleString('en-US');
const DATE = /\b(20\d{2})-(\d{2})-(\d{2})\b/;
const cutoff = new Date(TODAY + 'T00:00:00Z'); cutoff.setUTCDate(cutoff.getUTCDate() - DAYS);
// A file is generated when it SAYS SO ABOUT ITSELF - the H1 carries GENERATED
// (what the kernel's task-index generator writes), or a banner in the first five
// lines says "this file is generated/baked". A file that merely MENTIONS a
// generated file is not one (a grep hit tells you a string exists, not what it
// governs - the first draft refused memory.md for pointing at TASKS.md).
function isGenerated(text) {
  const head = text.split(/\r?\n/).slice(0, 5);
  if (/^#.*\bGENERATED\b/.test(head[0] || '')) return true;
  return head.some(l => /^(<!--\s*)?\**\s*(this file is (a )?(generated|baked)|generated by|auto-generated)/i.test(l.trim()));
}
const PREFS = /\b(preferences|patterns learned|lessons)\b/i;
const bandOf = f => (f <= 0.10 ? 'GREEN' : f <= 0.20 ? 'AMBER' : 'RED');

// ---- 1. the startup set, from context-weight (never a typed list) ----------
const weightArgs = ['--json', '--today', TODAY, '--window', String(WINDOW)];
if (ROOT_ARG) weightArgs.push('--root', String(ROOT_ARG));
// context-weight exits 1 (AMBER) / 2 (RED) by design, so a non-zero exit still carries JSON.
function measure() {
  let out;
  try { out = execFileSync(process.execPath, [path.join(__dirname, 'context-weight.mjs'), ...weightArgs], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); }
  catch (e) { out = (e.stdout || '').toString(); if (!out.trim()) { console.log('context-prune: could not measure the campus: ' + (e.stderr || e.message)); process.exit(2); } }
  try { return JSON.parse(out); }
  catch { return {resolution:{status:'incomplete'}, files:[], total_tokens:0, band:'UNKNOWN'}; }
}
const W = measure();
const errors = [];
if (W.resolution?.status !== 'complete' || !Number.isFinite(DAYS) || DAYS < 0 || !Number.isFinite(WINDOW) || WINDOW <= 0 || isNaN(cutoff)) {
  const result = {mode:APPLY ? 'apply' : 'propose', files:[], refused:[], errors:[{code:'PRUNE_INPUT_INCOMPLETE', detail:'Complete context measurement and valid days/date/window required'}]};
  console.log(JSON_OUT ? JSON.stringify(result, null, 2) : 'REFUSED: context measurement or prune arguments incomplete');
  process.exit(2);
}
const root = W.root;
const rel = abs => path.relative(root, abs);

// ---- 2. find aged units in one file -------------------------------------------
function isAged(text) { const m = text.match(DATE); if (!m) return false; const d = new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`); return !isNaN(d) && d < cutoff; }

function unitsIn(text, entryFile) {
  // Retain exact line endings and untouched spans. Eligibility is opt-in;
  // pinned/standing units override an archive-eligible marker.
  const lines = text.match(/[^\n]*\n|[^\n]+$/g) || [];
  const offsets = [0]; for (const line of lines) offsets.push(offsets.at(-1) + line.length);
  const eligible = value => /\[archive-eligible\]/i.test(value) && !/\[pinned\]|\bstanding[ -](rule|policy)\b/i.test(value);
  const units = [];
  let i = 0, inPrefs = !entryFile;
  const protectedSections = [];
  while (i < lines.length) {
    const h = lines[i].match(/^(#{1,6})\s+(.*)/);
    if (h) {
      const lv = h[1].length;
      while (protectedSections.length && protectedSections.at(-1).level >= lv) protectedSections.pop();
      protectedSections.push({level:lv, pinned:/\[pinned\]|\bstanding[ -](rule|policy)\b/i.test(h[2])});
      if (entryFile && lv <= 2) inPrefs = PREFS.test(h[2]);
      if (lv >= 2 && isAged(h[2]) && inPrefs && !protectedSections.some(s => s.pinned)) {
        let j = i + 1;
        while (j < lines.length) { const next = lines[j].match(/^(#{1,6})\s/); if (next && next[1].length <= lv) break; j++; }
        const content = lines.slice(i,j).join('');
        if (eligible(h[2]) && !/\[pinned\]|\bstanding[ -](rule|policy)\b/i.test(content)) {
          units.push({start:i,end:j,kind:'section',label:h[2].trim()}); i=j; continue;
        }
      }
      i++; continue;
    }
    const li = lines[i].match(/^([-*]|\d+\.)\s+(.*)/);
    if (li && inPrefs && isAged(li[2]) && !protectedSections.some(s => s.pinned)) {
      let j=i+1; while (j<lines.length && /^\s+\S/.test(lines[j])) j++;
      if (eligible(lines.slice(i,j).join(''))) { units.push({start:i,end:j,kind:'item',label:li[2].trim().slice(0,70)}); i=j; continue; }
    }
    i++;
  }
  for (const u of units) { u.text=text.slice(offsets[u.start],offsets[u.end]); u.tokens=tokens(u.text); }
  return {lines, units};
}

// ---- 3. plan ------------------------------------------------------------------
const plan = []; const refused = [];
for (const f of W.files) {
  if (f.missing) continue;
  const role = f.role || '';
  const isEntry = role.startsWith('entry');
  if (isEntry && !/chief of staff/.test(role)) continue;             // root redirects: never touched
  const abs = f.path;
  if (!abs || !contained(root, abs) || fs.lstatSync(f.source_path || abs).isSymbolicLink()) { refused.push({file:f.file, why:'path outside campus or symlink'}); continue; }
  if (ONLY && rel(abs) !== ONLY && f.file !== ONLY) continue;
  if (!/\.md$/i.test(abs)) continue;
  const text = fs.readFileSync(abs, 'utf8');
  if (isGenerated(text)) { refused.push({ file: rel(abs), tokens: f.tokens, why: 'declares itself generated - cap it in its generator, not here' }); continue; }
  const { lines, units } = unitsIn(text, isEntry);
  if (!units.length) continue;
  const saved = units.reduce((a, u) => a + u.tokens, 0);
  const archive = path.join(path.dirname(abs), 'archive', `${TODAY.slice(0, 7)}-${path.basename(abs, '.md')}.md`);
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const replacement = []; let cursor = 0;
  for (const u of units) {
    replacement.push(...lines.slice(cursor,u.start));
    replacement.push(`- *(archived ${TODAY} -> ${path.relative(path.dirname(abs),archive)})*` + eol);
    cursor=u.end;
  }
  replacement.push(...lines.slice(cursor));
  const moved = units.map(u => u.text);
  const replacementText = replacement.join('');
  plan.push({ abs, original:text, replacement:replacementText, moved,
    archiveText:`\n## Archived ${TODAY} from ${rel(abs)}\n\n` + moved.join('\n'),
    file: rel(abs), tokens: f.tokens, units, saved:tokens(text)-tokens(replacementText), archive: rel(archive), lines });
}
const before = W.total_tokens;
const savedAll = plan.reduce((a, p) => a + p.saved, 0);
const after = before - savedAll;

// ---- 4. report ----------------------------------------------------------------
function report() {
  if (JSON_OUT) { console.log(JSON.stringify({ campus: W.campus, date: TODAY, days: DAYS, mode: APPLY ? 'apply' : 'propose', before, after, band_before: W.band, band_after: bandOf(after / WINDOW), files: plan.map(p => ({ file: p.file, archive: p.archive, saved: p.saved, units: p.units.map(u => ({ kind: u.kind, label: u.label, tokens: u.tokens, lines: [u.start + 1, u.end] })) })), refused, errors }, null, 2)); return; }
  const o = [];
  o.push(`Context prune  -  ${W.campus}  -  ${TODAY}  -  entries older than ${DAYS} days  -  ${APPLY ? 'APPLY' : 'PROPOSE (nothing written)'}`);
  for (const p of plan) {
    o.push(''); o.push(`${p.file}  ${fmt(p.tokens)} tok  ->  move ${p.units.length} entr${p.units.length === 1 ? 'y' : 'ies'} (${fmt(p.saved)} tok) to ${p.archive}`);
    for (const u of p.units.slice(0, 12)) o.push(`    ${fmt(u.tokens).padStart(6)}  L${u.start + 1}-${u.end}  ${u.kind === 'section' ? '## ' : '- '}${u.label}`);
    if (p.units.length > 12) o.push(`           … ${p.units.length - 12} more`);
  }
  for (const r of refused) o.push(`\n${r.file}  ${fmt(r.tokens)} tok  ->  REFUSED: ${r.why}`);
  o.push('');
  o.push(`Startup ${fmt(before)} -> ${fmt(after)} tokens  (${(100 * before / WINDOW).toFixed(1)}% -> ${(100 * after / WINDOW).toFixed(1)}%)  ${W.band} -> ${bandOf(after / WINDOW)}`);
  if (!plan.length) o.push('No explicitly archive-eligible, unpinned units older than ' + DAYS + ' days in startup files.');
  else if (!APPLY) o.push('Run again with --apply to do it (archive first, verified, then pointers).');
  console.log(o.join('\n'));
}

if (!APPLY) { report(); process.exit(plan.length ? 1 : 0); }

// ---- 5. apply: preserve -> verify -> replace ------------------------------------
let failed = false;
for (const p of plan) {
  const result = applyPlan(root, p);
  if (!result.ok) { errors.push({file:p.file, ...result}); failed = true; }
  else p.applied = true;
}
if (!JSON_OUT) for (const error of errors) console.log(`FAIL: ${error.file}: ${error.detail}`);
report();
if (plan.length && !JSON_OUT && !failed) {
  const re = measure();
  console.log(`Re-measured after apply: ${fmt(re.total_tokens)} tokens -> ${re.band}`);
}
process.exit(failed ? 2 : 0);
